### ISSUE TITLE
Game Difficulty Forum - Post feedback on difficulty here!

### ISSUE THREAD

**Issue by IanKBovard** [HewlettPackard/hpe-hack-shack-attack#5]
Leave feedback on game difficulty here. 

A few things to know: (These may change with testing)
  The gameplay time is meant to be short. I would rather have people lose quickly and want to play 
  again, than become fatigued and lose the game out of boredom.

  Depending on how familiar someone is with video games I expect the scores to be:
  beginner: 25 - 75
  average: 76 - 300
  experienced: 301 - ...
  Currently, the game difficulty is designed around above average and experienced players. This may 
  change, as I don't know what the attendees will be like.

 The edges of the playfield are dark. This was intentional. It hides where the enemies spawn, and 
 is another way of creating difficulty.

Things that can be adjusted:

  Player Character:
    Move speed,
    Fire speed,
    Lives,
    Invincibility timer (when the pc gets hit the amount of time it takes for him to become tangible)
  
  Enemies:
    Move speed,
    Health,
    Spawn rate

  Power up:
    spawn rate

**Comment by jensy** [comment]
Hello, great stuff!

The difficulty tho is pretty hard, after playing it 10 games I got the hang of it, but knowing that people are going to be at a hectic event, I'd suggest people only have time for a couple of tries. I suggest decreasing the move speed of the enemies and let them spawn a little slower too.

Also, I think the IT monster looks a little bit too friendly, but maybe that's the point? :)

👏👏👏
